--- #YAML:1.0
name:                Games-Hack-Live
version:             0.4
abstract:            Perl script to ease playing games
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Expect:                        1.21
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Ph. Marek <pmarek@cpan.org>
